name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    timeout-minutes: 120 # There's a problem if a build takes over 2 hours.
    env:
      NO_STRIP: true
      CARGO_TARGET_DIR: ${{ github.workspace }}/cargo_target
      APPIMAGETOOL_VERSION: 1.9.1

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Required build packages
        if: ${{ matrix.os == 'ubuntu' }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglib2.0-dev

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-directories: ${{ env.CARGO_TARGET_DIR }}

      - name: Install Dioxus tooling
        run: cargo install dioxus-cli@^0.7

      - name: Build release
        run: cargo build --all-features --release

      - name: Generate bundled desktop apps
        run: dx bundle --all-features --release --verbose

      ### Linux only ###
      # Compress the appimage. Dioxus does not produce the best compression
      # for appimage size and performance by default.

      - id: appimagetool_cache
        uses: actions/cache@v4
        if: ${{ matrix.os == 'ubuntu' }}
        with:
          path: appimagetool.AppImage
          key: appimagetool-${{ env.APPIMAGETOOL_VERSION }}

      - name: Install appimagetool
        if: ( ${{ matrix.os == 'ubuntu' }} ) && ( steps.appimagetool_cache.outputs.cache-hit != 'true' )
        run: |
          wget -o appimagetool.AppImage "https://github.com/AppImage/appimagetool/releases/download/${APPIMAGETOOL_VERSION}/appimagetool-x86_64.AppImage"
          chmod +x appimagetool.AppImage

      - name: Replace Dioxus output with appimagetool output
        run: ./appimagetool.AppImage --appimage-extract-and-run target/dx/*/bundle/*/bundle/*/*.AppDir/ target/dx/*/bundle/*/bundle/*/*.AppImage

      ### ###

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_id }}-${{ matrix.os }}
          compression-level: 0 # Most of these formats are already compressed.
          if-no-files-found: error
          retention-days: 1 # Transient, just needs to pass to release.
          overwrite: true
          path: |
            target/dx/*/bundle/*/bundle/*/*.AppImage
            target/dx/*/bundle/*/bundle/*/*.deb
            target/dx/*/bundle/*/bundle/*/*.rpm
            target/dx/*/bundle/*/bundle/*/*.msi
            target/dx/*/bundle/*/bundle/*/*.exe
            target/dx/*/bundle/*/bundle/*/*.app
            target/dx/*/bundle/*/bundle/*/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v5
        with:
          pattern: build-${{ github.run_id }}-*
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            LICENSE
            target/dx/*/bundle/*/bundle/*/*.AppImage
            target/dx/*/bundle/*/bundle/*/*.deb
            target/dx/*/bundle/*/bundle/*/*.rpm
            target/dx/*/bundle/*/bundle/*/*.msi
            target/dx/*/bundle/*/bundle/*/*.exe
            target/dx/*/bundle/*/bundle/*/*.app
            target/dx/*/bundle/*/bundle/*/*.dmg
